version: '3.8'

services:
  # FastAPI Backend Service
  sentiment-api:
    build:
      context: ./reviews-sentiment-analysis
      dockerfile: Dockerfile
    container_name: sentiment-analysis-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./reviews-sentiment-analysis:/app
      - model_cache:/app/models
    networks:
      - sentiment-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Frontend Service
  sentiment-ui:
    build:
      context: ./reviews-analysis-ui
      dockerfile: Dockerfile
    container_name: sentiment-analysis-ui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://sentiment-api:8000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      sentiment-api:
        condition: service_healthy
    networks:
      - sentiment-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: sentiment-analysis-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - sentiment-api
      - sentiment-ui
    networks:
      - sentiment-network
    restart: unless-stopped

networks:
  sentiment-network:
    driver: bridge
    name: sentiment-analysis-network

volumes:
  model_cache:
    name: sentiment-models
    driver: local